version: '2'
services:
  coredns:
    image: coredns/coredns:1.5.0
    hostname: coredns
    environment:
      TZ: Asia/Shanghai
    stdin_open: true
    tty: true
    network_mode: bridge
    volumes:
    - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - /data/Corefile:/etc/coredns/Corefile:ro
    ports:
    - 53:53/tcp
    - 53:53/udp
    command:
    - -conf
    - /etc/coredns/Corefile
    mem_reservation: 268435456
    mem_limit: 1073741824
    cap_add:
    - NET_ADMIN
    - NET_BIND_SERVICE
    cap_drop:
    - SYS_ADMIN
    restart: always
    privileged: false
    logging:
      driver: json-file
    labels:
      io.rancher.scheduler.affinity:host_label: host_ip=172.31.10.4
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always

  ectd1:
    image: nuaays/etcd:v3.3.12
    hostname: etcd1
    environment:
      ETCD_NAME: etcd1
      ETCD_ADVERTISE_CLIENT_URLS: http://172.31.3.128:2379
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://172.31.3.128:2380
      ETCD_INITIAL_CLUSTER: etcd1=http://172.31.3.128:2380,etcd2=http://172.31.3.129:2380,etcd3=http://172.31.3.130:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: xcloud
      ETCD_DATA_DIR: /data-etcd
      ETCD_WAL_DIR: /data-wal
      ETCD_MAX_WALS: 5
      ETCD_HEARTBEAT_INTERVAL: 100
      ETCD_ELECTION_TIMEOUT: 1000
      ETCD_SNAPSHOT_COUNT: 5000
      ETCDCTL_API: '3'
      ETCD_ENABLE_V2: true
      TZ: Asia/Shanghai
    volumes:
    - /etc/localtime:/usr/share/zoneinfo/Asia/Shanghai:ro
    ports:
    - 2379:2379/tcp
    - 2380:2380/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: host_ip=172.31.3.128

  ectd2:
    image: nuaays/etcd:v3.3.12
    hostname: etcd2
    environment:
      ETCD_NAME: etcd2
      ETCD_ADVERTISE_CLIENT_URLS: http://172.31.3.129:2379
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://172.31.3.129:2380
      ETCD_INITIAL_CLUSTER: etcd1=http://172.31.3.128:2380,etcd2=http://172.31.3.129:2380,etcd3=http://172.31.3.130:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: xcloud
      ETCD_DATA_DIR: /data-etcd
      ETCD_WAL_DIR: /data-wal
      ETCD_MAX_WALS: 5
      ETCD_HEARTBEAT_INTERVAL: 100
      ETCD_ELECTION_TIMEOUT: 1000
      ETCD_SNAPSHOT_COUNT: 5000
      ETCDCTL_API: '3'
      ETCD_ENABLE_V2: true
      TZ: Asia/Shanghai
    volumes:
    - /etc/localtime:/usr/share/zoneinfo/Asia/Shanghai:ro
    ports:
    - 2379:2379/tcp
    - 2380:2380/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: host_ip=172.31.3.129

  ectd3:
    image: nuaays/etcd:v3.3.12
    hostname: etcd3
    environment:
      ETCD_NAME: etcd3
      ETCD_ADVERTISE_CLIENT_URLS: http://172.31.3.130:2379
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://172.31.3.130:2380
      ETCD_INITIAL_CLUSTER: etcd1=http://172.31.3.128:2380,etcd2=http://172.31.3.129:2380,etcd3=http://172.31.3.130:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: xcloud
      ETCD_DATA_DIR: /data-etcd
      ETCD_WAL_DIR: /data-wal
      ETCD_MAX_WALS: 5
      ETCD_HEARTBEAT_INTERVAL: 100
      ETCD_ELECTION_TIMEOUT: 1000
      ETCD_SNAPSHOT_COUNT: 5000
      ETCDCTL_API: '3'
      ETCD_ENABLE_V2: true
      TZ: Asia/Shanghai
    volumes:
    - /etc/localtime:/usr/share/zoneinfo/Asia/Shanghai:ro
    ports:
    - 2379:2379/tcp
    - 2380:2380/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: host_ip=172.31.3.130
